// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: find_user.sql

package database

import (
	"context"
)

const findUser = `-- name: FindUser :one
SELECT id, created_at, updated_at, name FROM users WHERE name = $1
`

func (q *Queries) FindUser(ctx context.Context, name string) (User, error) {
	row := q.db.QueryRowContext(ctx, findUser, name)
	var i User
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
	)
	return i, err
}
