// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_feed_by_url.sql

package database

import (
	"context"
)

const getFeedID = `-- name: GetFeedID :one
SELECT id, created_at, updated_at, name, url, user_id, last_fetched FROM feeds WHERE url = $1
`

func (q *Queries) GetFeedID(ctx context.Context, url string) (Feed, error) {
	row := q.db.QueryRowContext(ctx, getFeedID, url)
	var i Feed
	err := row.Scan(
		&i.ID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Name,
		&i.Url,
		&i.UserID,
		&i.LastFetched,
	)
	return i, err
}
