// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: get_feed_follows_for_user.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const getFeedFollows = `-- name: GetFeedFollows :many
SELECT feed_follows.feed_id, feeds.name, users.name FROM feed_follows JOIN feeds ON feed_follows.feed_id = feeds.id JOIN users ON feed_follows.user_id = users.id WHERE users.name = $1
`

type GetFeedFollowsRow struct {
	FeedID uuid.UUID
	Name   string
	Name_2 string
}

func (q *Queries) GetFeedFollows(ctx context.Context, name string) ([]GetFeedFollowsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFeedFollows, name)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeedFollowsRow
	for rows.Next() {
		var i GetFeedFollowsRow
		if err := rows.Scan(&i.FeedID, &i.Name, &i.Name_2); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
