// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: mark_feed_fetched.sql

package database

import (
	"context"

	"github.com/google/uuid"
)

const markFetched = `-- name: MarkFetched :exec
UPDATE feeds SET last_fetched = NOW(), updated_at = NOW() WHERE id = $1
`

func (q *Queries) MarkFetched(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markFetched, id)
	return err
}
